server:
  port: 8081


spring:
  application:
    name: skywalking-demo


  # datasource 数据源配置内容
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/swtest?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456