spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

server:
  port: 8099



##配置日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-value: 1
#      logic-not-delete-value: 0
pagehelper:
  auto-dialect: mysql

mybatis-plus:
  mapper-locations: "classpath*:/mapper/**/*.xml"
  type-aliases-package: com.mybatis.plux.model # 扫描的包路径
  global-config:
    banner: false # 关闭打印mybatis-plus的LOGO
    db-config:
      logicDeleteField: deleted
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true
  executor-type: batch
