spring:
  application:
    name: spring-boot-nacos
server:
  port: 8091

nacos:
  config:
    server-addr: 127.0.0.1:8848
    bootstrap:
      enable: true
      log-enable: true
    data-id: example
    type: yaml
    group: DEFAULT_GROUP
    namespace: