nacos:
  config:
    server-addr: 127.0.0.1:8848
    bootstrap:
      enable: true
      log-enable: true

    data-id: example-jasypt
    type: yaml
    group: DEFAULT_GROUP
    namespace:
    auto-refresh: true