nacos:
  config:
    server-addr: 127.0.0.1:8848
    bootstrap:
      enable: true
      log-enable: true
    data-id: example
    type: yaml
    group: DEFAULT_GROUP
    namespace: f13bc793-d72f-4903-9d11-7edf8a8feb88

